### ISSUE TITLE
SafeMapper no longer maps nullable to nullable

### ISSUE THREAD

**Issue by IronGeek** [unger/SafeMapper#5]
It seems the latest update introduced a new _regression_ for mapping between `nullable` types. These codes used to work in previous version (2.0.112), but failed and throws `exception` in latest version (2.0.118):

```csharp
SafeMap.Convert<int?, int?>(42);
SafeMap.Convert<bool?, bool?>(true);
SafeMap.Convert<Guid?, Guid?>(Guid.NewGuid());
SafeMap.Convert<DateTime?, DateTime?>(DateTime.Now);
SafeMap.Convert<TimeSpan?, TimeSpan?>(TimeSpan.FromDays(28));
```

**Comment by unger** [comment]
New nuget package (2.0.120) available that should solve this problem.
